from app.views import ExecutePOSTView
from payments.serializers import TokenizeSerializer, SaleSerializer


class TokenizeView(ExecutePOSTView):
    """
    API view that return token generated by PSP for card details provided
    in request body.
    """
    serializer_class = TokenizeSerializer


class SaleView(ExecutePOSTView):
    """
    API view that request sale on PSP for token provided in request body.
    """
    serializer_class = SaleSerializer
